[tool.poetry]
name = "powerpoint-image-exporter"
version = "0.1.0"
description = ""
authors = ["Tom Kierzkowski <52253+tjkierzkowski@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
python-pptx = "^0.6.18"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
coverage = "^5.2.1"
pytest-cov = "^2.10.1"
pytest-mock = "^3.3.1"

[tool.coverage.paths]
source = ["."]

[tool.coverage.run]
branch = true
source = ["powerpoint_image_exporter"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
